name: firefly-hibachi

services:
  # NOTE: Don't edit this
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  # NOTE: This is going to act like app/api
  api:
    build: ./api
    restart: unless-stopped
    volumes:
      - ./api/src:/app/src
      # - ./server.js:/app/server.js
      # - ./frontend:/app/frontend
    environment:
      - PORT=80
    env_file:
      - .env
    ports:
      - "8080:80"

  # NOTE: This is going to act like app/frontend
  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
      # - ../server.js:/app/../../server.js
      # - ./frontend/server.js:/app/server.js
      # - ./server.js:/app/server.js
      # - ./api/src:/app/src
    environment:
      - PORT=3000
    ports:
      - "3000:3000"


  # folder 3: /database
  database:
    image: mariadb:10.6
    restart: unless-stopped
    ports:
      # Make the DB accessible from outside of the Docker network if needed
      - 3307:3306
    volumes:
      # Mount a volume for mariadb's persistent files for lifecylce outside of stack
      - "./database/data:/var/lib/mysql"
      # Mount the db_schema directory into the container to be auto-read and created in the new db
      - "./database/db_schema:/docker-entrypoint-initdb.d"
    env_file:
      - .env